name: Update File

on:
  push:
    branches:
      - main

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Update file
      run: |
        curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
             -X PUT \
             -d '{"message":"Update file via API","content":"BASE64_ENCODED_CONTENT","sha":"FILE_SHA"}' \
             https://api.github.com/repos/${{ github.repository }}/contents/src/data/test.json